### ISSUE TITLE
Add segment length info to Precision-Recall curves?

### ISSUE THREAD

**Issue by urinieto** [urinieto/similarity_classification#2]
When computing the P and R for the different thresholds (in order tho choose the most optimal one), should we have into account the length of each segment? i.e., should we use something like the pair-wise clustering or should we treat each segment as a single binary value?

I would say we should keep the length information, since we want as much of each song covered as possible.

**Comment by bmcfee** [comment]
How are you proposing to use the length information?  I think this makes the most sense to incorporate into the dtw cost, but there are many ways to do it.

The general picture that I have in mind is an ROC curve where the threshold is varied over dtw cost, and the detections correspond to similarly-labeled segments.  Normalizing dtw cost in different ways (say, by length of the input segments) will produce different curves, which we can then compare and inspect later on.

Of course, this methodology isn't perfect, since the whole point is to avoid simply using segment labels to determine repetition, but I think it's close enough to get us useful data.

As for including length, I have a few ideas to compare:
- No normalization: use raw dtw cost of aligning sections `s` and `t`
- Minimum length: use the minimum duration (in seconds) `cost / min(d_s, d_t)`.  Note that these durations should be of the segments as aligned to the (sub-)beat boundaries.  This could get noisy for very short segments (ie, less than one beat), so maybe we need to smooth it a little.
- Maximum length: `cost / max(d_s, d_t)`
- Harmonic mean of length: `cost / hmean(d_s, d_t)`
- others?

**Comment by urinieto** [comment]
So the question is: if we incorporate the length in the DTW cost, then we no longer need to incorporate it when computing the ROC curve? You're probably right and we don't, but I'm not sure about it.

In any event, yes, we can try these 4 normalization types. We already have some scores from the SALAMI dataset in the `data` folder.
